INSERT INTO USER(UT_ID, FIO, PASSWORD)VALUES(2, "Азалханов Саид", "said2")
INSERT INTO USER(UT_ID, FIO, PASSWORD)VALUES(2, "Акрамов Халил", "halil3")
INSERT INTO USER(UT_ID, FIO, PASSWORD)VALUES(2, "Баранов Семён", "semen4")
INSERT INTO USER(UT_ID, FIO, PASSWORD)VALUES(2, "Братякин Кирилл", "kirill5")
INSERT INTO USER(UT_ID, FIO, PASSWORD)VALUES(2, "Головач Михаил", "mihail6")
INSERT INTO USER(UT_ID, FIO, PASSWORD)VALUES(2, "Гульмамедов Рахим", "rahim7") 
INSERT INTO USER(UT_ID, FIO, PASSWORD)VALUES(2, "Ким Юлия", "yuliya8")
INSERT INTO USER(UT_ID, FIO, PASSWORD)VALUES(2, "Логвинов Денис", "denis9")
INSERT INTO USER(UT_ID, FIO, PASSWORD)VALUES(2, "Мадинова Арзу", "arzu10")
INSERT INTO USER(UT_ID, FIO, PASSWORD)VALUES(2, "Похвала Ольга", "olya11")

